import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { LayerProvider } from "../contexts/LayerContext";
import { ProductionProvider } from "../contexts/ProductionContext";
import { WorkerProvider } from "../contexts//WorkerContext";
import { InventoryProvider } from "../contexts//InventoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductionProvider>
          <LayerProvider>
            <WorkerProvider>
              <InventoryProvider>{children}</InventoryProvider>
            </WorkerProvider>
          </LayerProvider>
        </ProductionProvider>
      </body>
    </html>
  );
}
