import type { Metadata } from "next";
import { Vazirmatn  } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import SideBar from "@/components/ui/sidebar";

const vazir = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "خط تولید",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={` ${vazir.variable} antialiased`}>
        <SideBar />

        {children}
        <Toaster />
      </body>
    </html>
  );
}
